build-tar: Remove traces of non-shipped files
Signed-off-by: Stefan Raspl <raspl@linux.vnet.ibm.com>

diff --git a/build-tar b/build-tar
--- a/build-tar
+++ b/build-tar
@@ -38,7 +38,7 @@ cp smc_pnet.c $build_dir;
 cp smcss.c $build_dir;
 cp ld_pre_smc.c $build_dir;
 cp Makefile $build_dir;
-sed -e '/^smc-tools.spec:/,+5d' Makefile > $build_dir/Makefile;
+sed -e '/^smc-tools.spec:/,+5d' Makefile | sed -e 's/ smc-tools.spec//' | sed -e 's/ af_smc.7//' | sed -e 's/ README.smctools//' > $build_dir/Makefile;
 cp LICENSE $build_dir;
 cp README.smctools $build_dir;
 cp af_smc.7 $build_dir;
@@ -47,6 +47,16 @@ cp smc_pnet.8 $build_dir;
 cp smc_run.in $build_dir;
 cp smc_run.8 $build_dir;
 
+cd $build_dir;
+num=`ls -1 | wc -l`;
+make >/dev/null 2>&1
+make clean >/dev/null
+if [ `ls -1 | wc -l` -ne $num ]; then
+	echo "Error: Number of files variies after a 'make'-'make clean' cycle"
+	exit 1;
+fi
+
+cd -;
 cd tmp;
 tar -zcvf ../smc-tools-$VERSION.tar.gz smc-tools-$VERSION | sed 's/^/   /';
 if [ $? -eq 0 ]; then
