smc_run: Add various command-line switches
Add switches to set send and receive buffer-sizes, as well as the universal
'-h' and '-v'.
This requires changes in the preload library. Values are passed on via env
variables SMC_SNDBUF and SMC_RCVBUF, and can be specified in Bytes either
plain, or using metric prefixes k/K and m/M. Which helps to take advantage
of this feature in absence of using smc_run.
Furthermore, we're limited by net.core.rmem_max and net.core.wmem_max, which
are set to 256k by default. Therefore, we raise those values if they are
less than what the user requests. This is documented in the man page.
While at it, reworked (simplified) the opts parsing logic a bit.

Signed-off-by: Stefan Raspl <raspl@linux.ibm.com>

diff --git a/smc_run b/smc_run
--- a/smc_run
+++ b/smc_run
@@ -11,27 +11,66 @@
 #
 LIB_NAME="libsmc-preload.so"
 
+
+function usage() {
+        echo;
+        echo "Usage: smc_run [ OPTIONS ] COMMAND";
+        echo;
+        echo "Run COMMAND using SMC for TCP sockets";
+        echo;
+        echo "   -d         enable debug mode";
+        echo "   -h         display this message";
+        echo "   -r <SIZE>  request receive buffer size in Bytes";
+        echo "   -t <SIZE>  request transmit buffer size in Bytes";
+        echo "   -v         display version info";
+}
+
+function check_size() {
+	if [[ ! "$1" =~ ^[0-9]+[k|K|m|M]?$ ]]; then
+		echo "Error: Invalid buffer size specified: '$1'";
+		exit 1;
+	fi
+	return
+}
+
+function adjust_core_net_max() {
+	case ${2: -1} in
+		k | K)	(( OPTARG=${2%?}*1024 ));;
+		m | M)	(( OPTARG=${2%?}*1048576 ));;
+		*)
+	esac
+	if [ `sysctl -n net.core.$1_max` -lt $OPTARG ]; then
+		sysctl -w net.core.$1_max=$OPTARG >/dev/null;
+	fi
+}
+
 #
 # Verify command line arguments and specify the preload library debug mode
 # if necessary.
 #
-command_line=$@
-debug_option=$(echo "$command_line" | cut -f 1 -d " ");
 SMC_DEBUG=0;
-while getopts ":d" opt; do
+while getopts "dhr:t:" opt; do
 	case $opt in
 		d)
-			SMC_DEBUG=1;
-			command_line=${command_line#"$debug_option"};
-			command_line=${command_line##\ };
-			;;
-		\?)
-			echo "`basename "$0"`: Error: Invalid option: -$OPTARG";
-			exit 1;
-			;;
+			SMC_DEBUG=1;;
+		h)	usage;
+			exit 0;;
+		r)	check_size $OPTARG;
+			adjust_core_net_max rmem $OPTARG;
+			export SMC_RCVBUF=$OPTARG;;
+		t)	check_size $OPTARG;
+			adjust_core_net_max wmem $OPTARG;
+			export SMC_SNDBUF=$OPTARG;;
+		v)	echo "smc_run utility, smc-tools-$VERSION";
+			exit;;
+		\?)	echo "`basename "$0"`: Error: Invalid option: -$OPTARG";
+			exit 1;;
 	esac
 done
-if [ "x$command_line" = "x" ]; then
+
+shift $(expr $OPTIND - 1);
+command_line=$@
+if [ "$command_line" == "" ]; then
 	echo "`basename "$0"`: Error: Missing command parameter";
 	exit 1;
 fi
