smc_run.bpf: An eBPF implemented smc_run with IPPROTO_SMC
Usage: smc_run.bpf COMMAND
Usage: smc_run.bpf [-h] [-v] [-s [load|unload]] [-p pid] [-n 0|1]
Usage: export SMC_RUN_BPF=1; smc_run COMMAND

Signed-off-by: D. Wythe <alibuda@linux.alibaba.com>

diff --git a/smc_run b/smc_run
--- a/smc_run
+++ b/smc_run
@@ -79,6 +79,16 @@ export SMC_DEBUG;
 #
 # Execute the specified command.
 #
+
+if [ -n "$SMC_RUN_BPF" ] && [ "$SMC_RUN_BPF" -ne 0 ]; then
+	smc_run.bpf -p $$ > /dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		exec "$@"
+		exit $?;
+	fi
+	# failover to AF_SMC with LD_PRELOAD
+fi
+
 export LD_PRELOAD=$LD_PRELOAD:$LIB_NAME;
 
 exec "$@"
