smc_rnics: Fix RoCE Express2 port display
The port attribute for RoCE Express2 cards is always '0', no matter what.
The reason is that there is one PCHID per port for these cards, and
therefore we always have a single port only per PCHID.
Users will likely have a different expectation/perception. A new attribute
will be added with a future kernel version.
This patch suppresses display of the port attribute unless we have accurate
information due to the new kernel version.

Signed-off-by: Stefan Raspl <raspl@linux.ibm.com>

diff --git a/smc_rnics.in b/smc_rnics.in
--- a/smc_rnics.in
+++ b/smc_rnics.in
@@ -17,14 +17,92 @@ function usage() {
 	echo;
 }
 
+function print_header() {
+	printf "     FID  Power  PCI ID        PCHID  Type           Port  PNET ID           Interface\n";
+	echo '-----------------------------------------------------------------------------------------';
+}
+
 function print_rnic() {
-	if [ $header -eq 0 ]; then
-		printf "     FID  Power  PCI ID        PCHID  Type           Port  PNET ID           Interface\n";
-		echo '-----------------------------------------------------------------------------------------';
-		header=1;
-	fi
 	printf "%8x  %-5s  %-12s  %-4s   %-14s %-4s  %-16s  %s\n" "$((16#$fid))" "$power" "$addr" "$pchid" "$dev_type" "$port" "$pnet" "$int";
 	(( printed++ ));
+}
+
+function print_rnics() {
+	# iterate over slots, as powered-off devices won't show elsewhere
+	for fid in `ls -1 /sys/bus/pci/slots`; do
+		cd /sys/bus/pci/slots/$fid;
+		fid="$fid";
+		if [ "$target" != "" ] && [ "$fid" != "$target" ]; then
+			continue;
+		fi
+		power=`cat power`;
+		interfaces="";
+		port="";
+		addr="";
+		int="";
+		if [ $power -eq 0 ]; then
+			# device not yet hotplugged
+			dev_type="";
+			pchid="";
+			pnet="";
+			print_rnic;
+			continue;
+		fi
+		# device is hotplugged - locate it
+		for dev in `ls -1 /sys/bus/pci/devices`; do
+			cd /sys/bus/pci/devices/$dev;
+			if [ "`cat function_id`" == "0x$fid" ]; then
+				addr=$dev;
+				break;
+			fi
+		done
+		if [ "$addr" == "" ]; then
+			echo "Error: No matching device found for FID $fid" >&2;
+			continue;
+		fi
+		cd /sys/bus/pci/devices/$addr;
+		id=`cat device`;
+		vend=`cat vendor`;
+		dev_type="${vend#0x}:${id#0x}";
+		if [ $rawIDs -eq 0 ]; then
+			case "$vend" in
+			"0x1014" ) # IBM
+				case "$id" in
+				"0x04ed") dev_type="ISM";
+					  port="n/a";
+					  int="n/a";;
+				"0x044b") continue;;		# zEDC
+				esac;;
+			"0x15b3" ) # Mellanox
+				case "$id" in
+				"0x1003" | \
+				"0x1004") dev_type="RoCE Express";;
+				"0x1016") dev_type="RoCE Express2";
+					  if [ -e port ]; then
+						port=`cat port`;
+						let port=$port-1;
+					  fi;;
+				esac;;
+			esac
+		fi
+		pchid="`cat pchid | sed 's/^0x//'`";
+		pnet="`cat util_string | tr -d '\000' | iconv -f IBM-1047 -t ASCII | cut -c 1-16`";
+		if [ -d net ]; then
+			interfaces="`ls -1 net`";
+		fi
+		if [ "$interfaces" == "" ]; then
+			print_rnic;
+			continue;
+		fi
+		# one device can have multiple interfaces (one per port)
+		for int in $interfaces; do
+			cd /sys/bus/pci/devices/$addr/net/$int;
+			if [ "$dev_type" == "RoCE Express" ] && [ -e dev_port ]; then
+				port=`cat dev_port`;
+			fi
+			print_rnic;
+		done
+	done
 }
 
 function format_fid() {
@@ -36,6 +114,16 @@ function format_fid() {
 	fi
 
 	res="`printf "%08x" $((16#$res))`";
+}
+
+function set_pnet_from_port() {
+	local idx;
+	local end;
+	local port=$1;
+
+	(( idx=16*$port+1 ))
+	(( end=$idx+15 ))
+	pnet=`echo "$pnetids" | cut -c $idx-$end`;
 }
 
 if [ "`uname -m`" != "s390x" ] && [ "`uname -m`" != "s390" ]; then
@@ -102,82 +190,8 @@ if [ "$action" != "print" ]; then
 	exit 0;
 fi
 
-header=0;
-# iterate over slots, as powered-off devices won't show elsewhere
-for fid in `ls -1 /sys/bus/pci/slots`; do
-	cd /sys/bus/pci/slots/$fid;
-	fid="$fid";
-	if [ "$target" != "" ] && [ "$fid" != "$target" ]; then
-		continue;
-	fi
-	power=`cat power`;
-	interfaces="";
-	port="";
-	addr="";
-	int="";
-	if [ $power -eq 0 ]; then
-		# device not yet hotplugged
-		dev_type="";
-		pchid="";
-		pnet="";
-		print_rnic;
-		continue;
-	fi
-	# device is hotplugged - locate it
-	for dev in `ls -1 /sys/bus/pci/devices`; do
-		cd /sys/bus/pci/devices/$dev;
-		if [ "`cat function_id`" == "0x$fid" ]; then
-			addr=$dev;
-			break;
-		fi
-	done
-	if [ "$addr" == "" ]; then
-		echo "Error: No matching device found for FID $fid" >&2;
-		continue;
-	fi
-	cd /sys/bus/pci/devices/$addr;
-	id=`cat device`;
-	vend=`cat vendor`;
-	dev_type="${vend#0x}:${id#0x}";
-	if [ $rawIDs -eq 0 ]; then
-		case "$vend" in
-		"0x1014" ) # IBM
-			case "$id" in
-			"0x04ed") dev_type="ISM";
-				  port="n/a";
-				  int="n/a";;
-			"0x044b") continue;;		# zEDC
-			esac;;
-		"0x15b3" ) # Mellanox
-			case "$id" in
-			"0x1003" | \
-			"0x1004") dev_type="RoCE Express";;
-			"0x1016") dev_type="RoCE Express2";;
-			esac;;
-		esac
-	fi
-	pchid="`cat pchid | sed 's/^0x//'`";
-	pnet="`cat util_string | tr -d '\000' | iconv -f IBM-1047 -t ASCII`";
-	if [ -d net ]; then
-		interfaces="`ls -1 net`";
-	fi
-	# one device can have multiple interfaces (one per port)
-	if [ "$interfaces" != "" ]; then
-		pnetids="$pnet";
-		for int in $interfaces; do
-			cd /sys/bus/pci/devices/$addr/net/$int;
-			if [ -e dev_port ]; then
-				port=`cat dev_port`;
-				(( idx=16*$port+1 ))
-				(( end=$idx+15 ))
-				pnet=`echo "$pnetids" | cut -c $idx-$end`;
-			fi
-			print_rnic;
-		done
-		continue;
-	fi
-	print_rnic;
-done
+print_header;
+print_rnics | sort -k 4;
 
 if [ "$target" != "" ] && [ $printed -eq 0 ]; then
 	exit 8;
